//
//  MCItem.h
//  CraftMii2
//
//  Created by qwertyoruiop on 19/07/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
typedef enum MCBlockType
{
    MCBlockTypeNoItem = -1,
    MCBlockTypeAir = 0x00,
    MCBlockTypeStone = 0x01,
    MCBlockTypeGrass = 0x02,
    MCBlockTypeDirt = 0x03,
    MCBlockTypeCobblestone = 0x04,
    MCBlockTypeWoodenPlank = 0x05,
    MCBlockTypeSapling = 0x06,
    MCBlockTypeBedrock = 0x07,
    MCBlockTypeWater = 0x08,
    MCBlockTypeStationaryWater = 0x09,
    MCBlockTypeLava = 0x0A,
    MCBlockTypeStationaryLava = 0x0B,
    MCBlockTypeSand = 0x0C,
    MCBlockTypeGravel = 0x0D,
    MCBlockTypeGoldOre = 0x0E,
    MCBlockTypeIronOre = 0x0F,
    MCBlockTypeCoalOre = 0x10,
    MCBlockTypeWood = 0x11,
    MCBlockTypeLeaves = 0x12,
    MCBlockTypeSponge = 0x13,
    MCBlockTypeGlass = 0x14,
    MCBlockTypeLapisLazuliOre = 0x15,
    MCBlockTypeLapisLazuliBlock = 0x16,
    MCBlockTypeDispenser = 0x17,
    MCBlockTypeSandstone = 0x18,
    MCBlockTypeNoteBlock = 0x19,
    MCBlockTypeBed_placed = 0x1A,
    MCBlockTypePoweredRail = 0x1B,
    MCBlockTypeDetectorRail = 0x1C,
    MCBlockTypeStickyPiston = 0x1D,
    MCBlockTypeCobweb = 0x1E,
    MCBlockTypeTallGrass = 0x1F,
    MCBlockTypeDeadShrub = 0x20,
    MCBlockTypePiston = 0x21,
    MCBlockTypePistonHead = 0x22,
    MCBlockTypeWool = 0x23,
    MCBlockTypeBlock36 = 0x24,
    MCBlockTypeYellowFlower = 0x25,
    MCBlockTypeRedRose = 0x26,
    MCBlockTypeBrownMushroom = 0x27,
    MCBlockTypeRedMushroom = 0x28,
    MCBlockTypeGoldBlock = 0x29,
    MCBlockTypeIronBlock = 0x2A,
    MCBlockTypeDoubleSlab = 0x2B,
    MCBlockTypeSlab = 0x2C,
    MCBlockTypeBrick = 0x2D,
    MCBlockTypeTnt = 0x2E,
    MCBlockTypeBookshelf = 0x2F,
    MCBlockTypeMossStone = 0x30,
    MCBlockTypeObsidian = 0x31,
    MCBlockTypeTorch = 0x32,
    MCBlockTypeFire = 0x33,
    MCBlockTypeMonsterSpawner = 0x34,
    MCBlockTypeWoodenStairs = 0x35,
    MCBlockTypeChest = 0x36,
    MCBlockTypeRedstoneWire_placed = 0x37,
    MCBlockTypeDiamondOre = 0x38,
    MCBlockTypeDiamondBlock = 0x39,
    MCBlockTypeCraftingTable = 0x3A,
    MCBlockTypeCrops = 0x3B,
    MCBlockTypeFarmland = 0x3C,
    MCBlockTypeFurnace = 0x3D,
    MCBlockTypeBurningFurnace = 0x3E,
    MCBlockTypeSignPost_placed = 0x3F,
    MCBlockTypeWoodenDoor_placed = 0x40,
    MCBlockTypeLadder = 0x41,
    MCBlockTypeMinecartTracks = 0x42,
    MCBlockTypeCobblestoneStairs = 0x43,
    MCBlockTypeWallSign_placed = 0x44,
    MCBlockTypeLever = 0x45,
    MCBlockTypeStonePressurePlate = 0x46,
    MCBlockTypeIronDoor_placed = 0x47,
    MCBlockTypeWoodenPressurePlate = 0x48,
    MCBlockTypeRedstoneOre = 0x49,
    MCBlockTypeGlowingRedstoneOre = 0x4A,
    MCBlockTypeRedstoneTorchOff_placed = 0x4B,
    MCBlockTypeRedstoneTorchOn = 0x4C,
    MCBlockTypeStoneButton = 0x4D,
    MCBlockTypeSnow = 0x4E,
    MCBlockTypeIce = 0x4F,
    MCBlockTypeSnowBlock = 0x50,
    MCBlockTypeCactus = 0x51,
    MCBlockTypeClay = 0x52,
    MCBlockTypeSugarCane_placed = 0x53,
    MCBlockTypeJukebox = 0x54,
    MCBlockTypeFence = 0x55,
    MCBlockTypePumpkin = 0x56,
    MCBlockTypeNetherrack = 0x57,
    MCBlockTypeSoulSand = 0x58,
    MCBlockTypeGlowstone = 0x59,
    MCBlockTypePortal = 0x5A,
    MCBlockTypeJackOLantern = 0x5B,
    MCBlockTypeCake_placed = 0x5C,
    MCBlockTypeRedstoneRepeaterOff_placed = 0x5D,
    MCBlockTypeRedstoneRepeaterOn_placed = 0x5E,
    MCBlockTypeLockedChest = 0x5F,
    MCBlockTypeTrapdoor = 0x60,
    MCBlockTypeHiddenSilverfish = 0x61,
    MCBlockTypeStoneBricks = 0x62,
    MCBlockTypeHugeBrownMushroom = 0x63,
    MCBlockTypeHugeRedMushroom = 0x64,
    MCBlockTypeIronBars = 0x65,
    MCBlockTypeGlassPane = 0x66,
    MCBlockTypeMelon = 0x67,
    MCBlockTypePumpkinStem = 0x68,
    MCBlockTypeMelonStem = 0x69,
    MCBlockTypeVines = 0x6A,
    MCBlockTypeFenceGate = 0x6B,
    MCBlockTypeBrickStairs = 0x6C,
    MCBlockTypeStoneBrickStairs = 0x6D,
    MCBlockTypeMycelium = 0x6E,
    MCBlockTypeLilyPad = 0x6F,
    MCBlockTypeNetherBrick = 0x70,
    MCBlockTypeNetherBrickFence = 0x71,
    MCBlockTypeNetherBrickStairs = 0x72,
    MCBlockTypeNetherWart_placed = 0x73,
    MCBlockTypeEnchantmentTable_placed = 0x74,
    MCBlockTypeBrewingStand_placed = 0x75,
    MCBlockTypeCauldron_placed = 0x76,
    MCBlockTypeEndPortal = 0x77,
    MCBlockTypeEndPortalFrame = 0x78,
    MCBlockTypeEndStone = 0x79,
    MCBlockTypeDragonEgg = 0x7A,
    MCBlockTypeRedstoneLamp_inactive = 0x7B,
    MCBlockTypeRedstoneLamp_active = 0x7C,
    MCBlockTypeWoodenDoubleSlab = 0x7D,
    MCBlockTypeWoodenSlab = 0x7E,
    MCBlockTypeCocoaPlant = 0x7F,
    MCBlockTypeSandstoneStairs = 0x80,
    MCBlockTypeEmeraldOre = 0x81,
    MCBlockTypeEnderChest = 0x82,
    MCBlockTypeTripwireHook = 0x83,
    MCBlockTypeTripwire = 0x84,
    MCBlockTypeEmeraldBlock = 0x85,
    MCBlockTypeIronShovel = 0x100,
    MCBlockTypeIronPickaxe = 0x101,
    MCBlockTypeIronAxe = 0x102,
    MCBlockTypeFlintAndSteel = 0x103,
    MCBlockTypeApple = 0x104,
    MCBlockTypeBow = 0x105,
    MCBlockTypeArrow = 0x106,
    MCBlockTypeCoal = 0x107,
    MCBlockTypeDiamond = 0x108,
    MCBlockTypeIronIngot = 0x109,
    MCBlockTypeGoldIngot = 0x10A,
    MCBlockTypeIronSword = 0x10B,
    MCBlockTypeWoodenSword = 0x10C,
    MCBlockTypeWoodenShovel = 0x10D,
    MCBlockTypeWoodenPickaxe = 0x10E,
    MCBlockTypeWoodenAxe = 0x10F,
    MCBlockTypeStoneSword = 0x110,
    MCBlockTypeStoneShovel = 0x111,
    MCBlockTypeStonePickaxe = 0x112,
    MCBlockTypeStoneAxe = 0x113,
    MCBlockTypeDiamondSword = 0x114,
    MCBlockTypeDiamondShovel = 0x115,
    MCBlockTypeDiamondPickaxe = 0x116,
    MCBlockTypeDiamondAxe = 0x117,
    MCBlockTypeStick = 0x118,
    MCBlockTypeBowl = 0x119,
    MCBlockTypeMushroomStew = 0x11A,
    MCBlockTypeGoldSword = 0x11B,
    MCBlockTypeGoldShovel = 0x11C,
    MCBlockTypeGoldPickaxe = 0x11D,
    MCBlockTypeGoldAxe = 0x11E,
    MCBlockTypeString = 0x11F,
    MCBlockTypeFeather = 0x120,
    MCBlockTypeGunpowder = 0x121,
    MCBlockTypeWoodenHoe = 0x122,
    MCBlockTypeStoneHoe = 0x123,
    MCBlockTypeIronHoe = 0x124,
    MCBlockTypeDiamondHoe = 0x125,
    MCBlockTypeGoldHoe = 0x126,
    MCBlockTypeSeeds = 0x127,
    MCBlockTypeWheat = 0x128,
    MCBlockTypeBread = 0x129,
    MCBlockTypeLeatherHelmet = 0x12A,
    MCBlockTypeLeatherChestplate = 0x12B,
    MCBlockTypeLeatherLeggings = 0x12C,
    MCBlockTypeLeatherBoots = 0x12D,
    MCBlockTypeChainmailHelmet = 0x12E,
    MCBlockTypeChainmailChestplate = 0x12F,
    MCBlockTypeChainmailLeggings = 0x130,
    MCBlockTypeChainmailBoots = 0x131,
    MCBlockTypeIronHelmet = 0x132,
    MCBlockTypeIronChestplate = 0x133,
    MCBlockTypeIronLeggings = 0x134,
    MCBlockTypeIronBoots = 0x135,
    MCBlockTypeDiamondHelmet = 0x136,
    MCBlockTypeDiamondChestplate = 0x137,
    MCBlockTypeDiamondLeggings = 0x138,
    MCBlockTypeDiamondBoots = 0x139,
    MCBlockTypeGoldHelmet = 0x13A,
    MCBlockTypeGoldChestplate = 0x13B,
    MCBlockTypeGoldLeggings = 0x13C,
    MCBlockTypeGoldBoots = 0x13D,
    MCBlockTypeFlint = 0x13E,
    MCBlockTypeRawPorkchop = 0x13F,
    MCBlockTypeCookedPorkchop = 0x140,
    MCBlockTypePainting = 0x141,
    MCBlockTypeGoldenApple = 0x142,
    MCBlockTypeSign = 0x143,
    MCBlockTypeWoodenDoor = 0x144,
    MCBlockTypeBucket = 0x145,
    MCBlockTypeWaterBucket = 0x146,
    MCBlockTypeLavaBucket = 0x147,
    MCBlockTypeMinecart = 0x148,
    MCBlockTypeSaddle = 0x149,
    MCBlockTypeIronDoor = 0x14A,
    MCBlockTypeRedstone = 0x14B,
    MCBlockTypeSnowball = 0x14C,
    MCBlockTypeBoat = 0x14D,
    MCBlockTypeLeather = 0x14E,
    MCBlockTypeMilkBucket = 0x14F,
    MCBlockTypeClayBrick = 0x150,
    MCBlockTypeClayBall = 0x151,
    MCBlockTypeSugarCane = 0x152,
    MCBlockTypePaper = 0x153,
    MCBlockTypeBook = 0x154,
    MCBlockTypeSlimeball = 0x155,
    MCBlockTypeStorageMinecart = 0x156,
    MCBlockTypePoweredMinecart = 0x157,
    MCBlockTypeEgg = 0x158,
    MCBlockTypeCompass = 0x159,
    MCBlockTypeFishingRod = 0x15A,
    MCBlockTypeClock = 0x15B,
    MCBlockTypeGlowstoneDust = 0x15C,
    MCBlockTypeRawFish = 0x15D,
    MCBlockTypeCookedFish = 0x15E,
    MCBlockTypeInkSac = 0x15F,
    MCBlockTypeBone = 0x160,
    MCBlockTypeSugar = 0x161,
    MCBlockTypeCake = 0x162,
    MCBlockTypeBed = 0x163,
    MCBlockTypeRedstoneRepeater = 0x164,
    MCBlockTypeCookie = 0x165,
    MCBlockTypeMap = 0x166,
    MCBlockTypeShears = 0x167,
    MCBlockTypeMelonSlice = 0x168,
    MCBlockTypePumpkinSeeds = 0x169,
    MCBlockTypeMelonSeeds = 0x16A,
    MCBlockTypeRawBeef = 0x16B,
    MCBlockTypeSteak = 0x16C,
    MCBlockTypeRawChicken = 0x16D,
    MCBlockTypeCookedChicken = 0x16E,
    MCBlockTypeRottenFlesh = 0x16F,
    MCBlockTypeEnderPearl = 0x170,
    MCBlockTypeBlazeRod = 0x171,
    MCBlockTypeGhastTear = 0x172,
    MCBlockTypeGoldNugget = 0x173,
    MCBlockTypeNetherWart = 0x174,
    MCBlockTypePotion = 0x175,
    MCBlockTypeGlassBottle = 0x176,
    MCBlockTypeSpiderEye = 0x177,
    MCBlockTypeFermentedSpiderEye = 0x178,
    MCBlockTypeBlazePowder = 0x179,
    MCBlockTypeMagmaCream = 0x17A,
    MCBlockTypeBrewingStand = 0x17B,
    MCBlockTypeCauldron = 0x17C,
    MCBlockTypeEyeOfEnder = 0x17D,
    MCBlockTypeGlisteringMelon = 0x17E,
    MCBlockTypeSpawnEgg = 0x17F,
    MCBlockTypeBottleOEnchanting = 0x180,
    MCBlockTypeFireCharge = 0x181,
    MCBlockTypeBookAndQuill = 0x182,
    MCBlockTypeWrittenBook = 0x183,
    MCBlockTypeEmerald = 0x184,
    MCBlockTypeThirteenDisc = 0x8D0,
    MCBlockTypeCatDisc = 0x8D1,
    MCBlockTypeBlocksDisc = 0x8D2,
    MCBlockTypeChirpDisc = 0x8D3,
    MCBlockTypeFarDisc = 0x8D4,
    MCBlockTypeMallDisc = 0x8D5,
    MCBlockTypeMellohiDisc = 0x8D6,
    MCBlockTypeStalDisc = 0x8D7,
    MCBlockTypeStradDisc = 0x8D8,
    MCBlockTypeWardDisc = 0x8D9,
    MCBlockTypeElevenDisc = 0x8DA,
}   MCBlockType;
typedef enum MCToolLevel 
{
    MCToolLevelWood     = 0,
    MCToolLevelStone    = 1,
    MCToolLevelIron     = 2,
    MCToolLevelGold     = 5,
    MCToolLevelDiamond  = 3
}
MCToolLevel;
typedef enum MCBlockTool 
{
    MCBlockToolNone,
    MCBlockToolShovel,
    MCBlockToolPickaxe,
    MCBlockToolAxe,
    MCBlockToolSword,
    MCBlockToolShears,
    MCBlockToolDynamic
} MCBlockTool;
typedef struct MCTool
{
    MCBlockTool tool;
    MCToolLevel level;
} MCTool;
typedef enum MCBlockTrasparency
{
    MCBlockTrasparencyNone,
    MCBlockTrasparencyHigh,
    MCBlockTrasparencyMedium,
    MCBlockTrasparencyLow
} MCBlockTrasparency;
typedef enum MCMaterial
{
    MCMaterialCactus,
    MCMaterialCake,
    MCMaterialClay,
    MCMaterialCrops,
    MCMaterialDiamond,
    MCMaterialDirt,
    MCMaterialFire,
    MCMaterialGlass,
    MCMaterialGold,
    MCMaterialIce,
    MCMaterialIron,
    MCMaterialLava,
    MCMaterialLeaves,
    MCMaterialNoMaterial,
    MCMaterialPortal,
    MCMaterialPumpkin,
    MCMaterialRedstone,
    MCMaterialSand,
    MCMaterialSnow,
    MCMaterialSnowBlock,
    MCMaterialSponge,
    MCMaterialStone,
    MCMaterialTnt,
    MCMaterialWater,
    MCMaterialWood,
    MCMaterialWool
} MCMaterial;
typedef struct MCItem
{
    short               value;
    NSString*           name;
    char                stackHeight;
    BOOL                placeable;
    BOOL                activatable;
    BOOL                physical;
    BOOL                diggable;
    BOOL                blockActivatable;
    BOOL                safe;
    float               hardness;
    BOOL                enchantable;
    MCMaterial          material;
} MCItem;
extern MCItem itemTable[];
extern MCItem getItem(short value, char metadata);
extern double blockStrengthPerTick(MCTool tool, MCItem block, BOOL onGround, BOOL underwater);